docs/.vuepress/styles/index.styl, docs/guide/README.md
=> feat: add custom mermaid theme + rework diagrams

.babelrc, client/src/index.tsx, package.json, tsconfig.json, yarn.lock
=> fix: parcel config for building antd components

client/src/components/Sidebar.tsx, client/src/modules/actions.ts, handlers/admin.go, handlers/mocks.go, server/admin_server.go, server/middlewares.go, server/mock_server.go, services/mocks.go, types/history.go
J'ai mis un nom de session par défaut (Session #1, Session #2, etc.) et côté UI je crée la session tout de suite, si on veut la nommer on l'édite. C'est plus fluide je trouve :)
=> Backend improvements

client/src/modules/epics.ts, client/src/modules/types.ts, package.json, yarn.lock
Should remove the parcel warning on build
=> Remove io ts reporters

client/src/components/Code.tsx
=> feat: display collapse component when body size is to huge

.gitignore, client/src/components/History.scss, client/src/components/History.tsx, client/src/components/Mocks.scss, client/src/components/Mocks.tsx, client/src/modules/actions.ts, client/src/modules/reducers.ts, client/src/modules/utils.test.ts, client/src/modules/utils.ts, jest.config.js, package.json, yarn.lock
Fix #87 
[Capture vidéo](https://i.imgur.com/0ZzAqF3.gifv)
=> Create mock from request

client/src/components/Code.tsx, client/src/components/Mocks.tsx
=> make mock editor non collapsible

docs/.vuepress/config.js, package.json, yarn.lock
J'ai rajouté la variable d'env GA_ID sur Netlify
=> add google analytics to vuepress docs

client/src/components/History.tsx, client/src/components/Mocks.tsx, client/src/components/Sidebar.tsx, docs/technical-documentation/api.md, server/handlers/admin.go
=> minor changes

client/src/components/Mocks.tsx, client/src/modules/actions.ts, client/src/modules/epics.ts
POST on /mocks with "session" query param explicitely creates a new session, not what we want :D
=> fix 'add mocks' from the ui

docs/.vuepress/public/smocker.schema.json, docs/technical-documentation/mock-definition.md, server/types/mock.go, tests/data/proxy_mock_list.yml, tests/features/set_mocks.yml, tests/features/use_mocks.yml
=> fix: proxy should not follow redirect

tests/features/use_mocks.yml
Until postmanlabs/httpbin#617 is fixed
=> fix(temp): disable httpbin redirect tests

.gitignore, .travis.yml, Makefile, README.md, go.mod, go.sum, main_test.go, server/admin_server.go, server/mock_server.go, server/types/matchers_test.go
Proof of concept for code coverage with Venom tests
See: https://codecov.io/gh/Thiht/smocker/branch/coverage
=> Init code coverage with codecov

docs/.vuepress/public/smocker.schema.json, docs/technical-documentation/mock-definition.md, server/types/mock.go, tests/data/proxy_mock_list.yml, tests/features/set_mocks.yml, tests/features/use_mocks.yml
=> feat: new proxy keep host option

docs/.vuepress/public/smocker.schema.json, docs/technical-documentation/mock-definition.md, server/types/mock.go, tests/data/proxy_mock_list.yml, tests/features/set_mocks.yml, tests/features/use_mocks.yml
=> feat: proxy headers

.gitignore, Caddyfile, client/components/History.scss, client/components/History.tsx, yarn.lock
=> Issue 154 filters

client/components/History.tsx
The pagination was not updated when applying a filter
=> fix history display

server/types/matchers.go
=> fix: MarshalYAML method for BodyMatcher which caused problems during the persistence of mocks

server/handlers/mocks.go, server/types/history.go, server/types/matchers.go, server/types/mock.go, tests/data/matcher_mock_list.yml, tests/features/set_mocks.yml, tests/features/use_mocks.yml
=> fix: add mutex to avoid race conditions on time count + support body matcher for url encoded forms

server/services/persistence.go
=> revert: persistence service to clean up before saving sessions rather than afterwards
